name: Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: 'job-tracker-api'
  AZURE_WEBAPP_PACKAGE_PATH: './src'
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: Download spaCy model
      run: python -m spacy download en_core_web_sm

    - name: Run Python tests
      run: |
        cd src
        python -m pytest tests/ -v || echo "No tests found"

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Upload frontend artifact
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: frontend/dist

  deploy-backend:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        startup-command: 'uvicorn api.main:app --host 0.0.0.0 --port 8000'

  deploy-frontend:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3

    - name: Download frontend artifact
      uses: actions/download-artifact@v3
      with:
        name: frontend-build
        path: frontend/dist

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "frontend/dist"
        api_location: ""
        output_location: ""

  create-azure-resources:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group
      run: |
        az group create --name rg-job-tracker --location eastus

    - name: Create Storage Account
      run: |
        az storage account create \
          --name jobtrackerstorage${{ github.run_number }} \
          --resource-group rg-job-tracker \
          --location eastus \
          --sku Standard_LRS

    - name: Create Blob Container
      run: |
        az storage container create \
          --name jobtracker \
          --account-name jobtrackerstorage${{ github.run_number }} \
          --auth-mode login

    - name: Create App Service Plan
      run: |
        az appservice plan create \
          --name plan-job-tracker \
          --resource-group rg-job-tracker \
          --sku B1 \
          --is-linux

    - name: Create Web App
      run: |
        az webapp create \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group rg-job-tracker \
          --plan plan-job-tracker \
          --runtime "PYTHON|3.11"

    - name: Configure App Settings
      run: |
        az webapp config appsettings set \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group rg-job-tracker \
          --settings \
          RAPIDAPI_KEY="${{ secrets.RAPIDAPI_KEY }}" \
          EMAIL_ADDRESS="${{ secrets.EMAIL_ADDRESS }}" \
          EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}" \
          AZURE_STORAGE_CONNECTION_STRING="${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
